
source 'https://cdn.cocoapods.org/'

platform :ios, '15.0'

target 'ZscalerSDKSampleApp' do
  use_frameworks!
  pod 'Firebase/Crashlytics'
  pod 'ZscalerSDK', :path => '../../'

  target 'ZscalerSDKSampleAppTests' do
  end

  target 'ZscalerSDKSampleAppUITests' do
  end
end